name: "demo"

inputs:
  event_name:
    description: "override github.event_name"
    required: false
    default: ${{ github.event_name }}
  context:
    description: "override context"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Before install
      env:
        CONT: pippo
      run: echo $CONT
      shell: bash
