name: 'read shared file and set environment variables'
inputs:
  varFilePath:
    description: ""
    required: false
    default: ./.github/variables/variables.yml
runs:
  using: "composite"
  steps:
    - uses: mikefarah/yq@master
      with:
        cmd: yq '.env' '${{ inputs.varfilePath }}'
    - name: Reuse a variable obtained in another step
      run: "echo ${{ steps.get_username.outputs.result }} | sed s'/: /=/'g >> $GITHUB_ENV"
      shell: bash
    - run: env
      shell: bash

