name: "read shared file and set environment variables"
inputs:
  var-file:
    description: ""
    required: false
    default: ./.github/variables/variables.yml
runs:
  using: "composite"
  steps:
    - name: order 66
      shell: bash
      if: ${{ !contains(github.event.head_commit.message , '[affected:*]') && !github.event.pull_request.merged}}
      run: |
        VAR_A="A"
        VAR_B="B"
        VAR_C="C"
        {
          echo "VAR_A=$VAR_A";
          echo "VAR_B=$VAR_B";
          echo "VAR_C=$VAR_C";
          echo "BREAK_ACTION=true";
        } >> $GITHUB_ENV
    - name: order 67
      shell: bash
      run: |
        echo "VAR_A=$VAR_A";
        echo "VAR_B=$VAR_B";
        echo "VAR_C=$VAR_C";
    - name: commit msg
      shell: bash
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: |
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE;"
        echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }};"

    - name: commit IF msg
      id: affected
      if: ${{ contains(github.event.head_commit.message , '[affected:*]') }}
      shell: bash
      run: |
        echo "IF [affected:-]";
        echo "AFFECTED=true" >> $GITHUB_OUTPUT

    - name: NOT commit IF msg
      id: notaffected
      if: ${{ ! contains(github.event.head_commit.message , '[affected:*]') }}
      shell: bash
      run: |
        echo "NOT IF [affected:*]";
        echo "AFFECTED=false" >> $GITHUB_OUTPUT


    - name: stage2
      if: ${{ env.VAR_A  == 'A' || env.BREAK_ACTION == 'true' }}
      shell: bash
      run: |
        echo "A";
        echo "BASE_HASH=origin/${{ github.ref_name }}";
        echo AFFECTED OUTPUT: ${{ steps.affected.outputs.AFFECTED }};
        echo AFFECTED OUTPUT *: ${{ toJson(steps.affected.outputs.*) }};
        echo NOT AFFECTED OUTPUT: ${{ steps.notaffected.outputs.AFFECTED }};
        echo NOT AFFECTED OUTPUT *: ${{ steps.notaffected.outputs.* }};

    - name: stage3
      if: ${{ env.BREAK_ACTION != 'false' || env.VAR_A  != 'A'}}
      shell: bash
      run: |
        echo "stage3";
        echo "EVAL COND: ${{ env.BREAK_ACTION != 'false' || env.VAR_A  != 'A'}}";
