name: 'read shared file and set environment variables'
inputs:
  var-file:
    description: ""
    required: false
    default: ./.github/variables/variables.yml
runs:
  using: "composite"
  steps:
    - name: order 66
      shell: bash
      run: |
        VAR_A="A"
        VAR_B="B"
        VAR_C="C"
        {
          echo "VAR_A=$VAR_A";
          echo "VAR_B=$VAR_B";
          echo "VAR_C=$VAR_C";
        } >> $GITHUB_ENV
    - name: order 67
      shell: bash
      run: |
        echo "VAR_A=$VAR_A";
        echo "VAR_B=$VAR_B";
        echo "VAR_C=$VAR_C";
    - name: commit msg
      shell: bash
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: |
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE;"