name: 'read shared file and set environment variables'
inputs:
  var-file:
    description: ""
    required: false
    default: ./.github/variables/variables.yml
runs:
  using: "composite"
  steps:
    - run: cat ${{ inputs.var-file }}
      shell: bash
    - run: |
        yq '.env' '${{ inputs.var-file }}' | sed s'/: /=/'g >> $GITHUB_ENV"
      shell: bash
    - run: |
        env | sort
      shell: bash