name: 'read shared file and set environment variables'
inputs:
  var-file:
    description: ""
    required: false
    default: ./.github/variables/variables.yml
runs:
  using: "composite"
  steps:
    - run: cat ${{ inputs.var-file }}
      shell: bash
    - run: |
        yq '.. style="" | .env' '${{ inputs.var-file }}' | sed s'/: /=/'g > tmp
        while read ENVVAR; do
          echo "$ENVVAR" >> $GITHUB_ENV
        done < "tmp"
      shell: bash
    - run: |
        env | sort
      shell: bash
