name: "read shared file and set environment variables"
inputs:
  var-file:
    description: ""
    required: false
    default: ./.github/variables/variables.yml
runs:
  using: "composite"
  steps:
    - name: order 66
      shell: bash
      run: |
        VAR_A="A"
        VAR_B="B"
        VAR_C="C"
        {
          echo "VAR_A=$VAR_A";
          echo "VAR_B=$VAR_B";
          echo "VAR_C=$VAR_C";
        } >> $GITHUB_ENV
    - name: order 67
      shell: bash
      run: |
        echo "VAR_A=$VAR_A";
        echo "VAR_B=$VAR_B";
        echo "VAR_C=$VAR_C";
    - name: commit msg
      shell: bash
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: |
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE;"
        echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }};"

    - name: commit IF msg
      id: affected
      if: ${{ contains(github.event.head_commit.message , '[affected:*]') }}
      shell: bash
      run: |
        echo "IF [affected:-]";
        echo "AFFECTED=true" >> $GITHUB_OUTPUT

    - name: NOT commit IF msg
      id: notaffected
      if: ${{ ! contains(github.event.head_commit.message , '[affected:*]') }}
      shell: bash
      run: |
        echo "NOT IF [affected:*]";

    - name: stage2
      if: ${{ env.VAR_A  == 'A' }}
      shell: bash
      run: |
        echo "A";
        echo "BASE_HASH=origin/${{ github.ref_name }}";
