on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
jobs:
  vscode-server:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: install vscode
        run: |
          sudo apt update
          sudo apt install gnupg2 software-properties-common apt-transport-https curl
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
          sudo apt update
          sudo apt install code
      - name: run vscode tunnel
        run: code tunnel --accept-server-license-terms --random-name