name: 'use other action to read tag'
inputs:
  array:
    description: 'packages to cache'
    required: false
    type: string
    default: 'default0 default1'

runs:
  using: "composite"
  steps:
    - name: action echo
      shell: bash
      run: |
        packages=( $(echo ${{ inputs.array }}) )
        for i in "${packages[@]}"; do
          echo "$i"
        done