name: 'use other action to read tag'
inputs:
  array:
    description: 'packages to cache'
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: action echo
      shell: bash
      run: |
        for i in ( '${{ inputs.array }}' ); do
          echo "$i"
        done