name: "artifacts"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
env:
  JOB_CACHE_PATH: /tmp/node-cache-${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  CACHE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}
  RESTORE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}


jobs:
  stage0:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: echo "ciao" out.log
      - run: ls -la
  stage1:
    runs-on: ubuntu-22.04
    steps:
      - run: ls -la

  stage2:
    needs: upload
    runs-on: ubuntu-22.04
    steps:
      - run: ls pre-upload: