name: "artifacts"

on:
  push:
    branches:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
env:
  JOB_CACHE_PATH: /tmp/node-cache-${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  CACHE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}
  RESTORE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}


jobs:
  dry-download:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: pre-artifacts/
          name: my-artifact-${{ github.ref_name }}
      - run: ls -R
      - run: cat pre-artifacts/*
  upload:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: mkdir artifacts
      - run: echo hello > artifacts/world.txt
      - run: echo pluto > artifacts/pluto.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact-${{ github.ref_name }}
          path: artifacts/

  download:
    needs: upload
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts/
          name: my-artifact-${{ github.ref_name }}
      - run: ls -R
      - run: cat artifacts/*