name: "dev-build"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
env:
  JOB_CACHE_PATH: /tmp/node-cache-${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  CACHE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}
  RESTORE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}


jobs:
  stage0:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Cache tmp folder
        id: cache-tmp
        uses: actions/cache@v3
        with:
          path: ${{ env.JOB_CACHE_PATH }}
          key: ${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ env.RESTORE_KEY }}
      - run: ls -lh /tmp
      - run: ls -lh ${JOB_CACHE_PATH}/ || true
      - run: mkdir -p ${JOB_CACHE_PATH}
      - run: touch ${JOB_CACHE_PATH}/tempfile-${COMMIT_SHA}
      - run: echo "test" > ${JOB_CACHE_PATH}/tempfile-${COMMIT_SHA}
      - run: cat ${JOB_CACHE_PATH}/tempfile-${COMMIT_SHA}
      - run: ls -lh ${JOB_CACHE_PATH}/

  stage1:
    needs: stage0
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2    
      - name: Cache tmp folder
        id: cache-tmp
        uses: actions/cache@v3
        with:
          path: ${{ env.JOB_CACHE_PATH }}
          key: ${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ env.RESTORE_KEY }}
      - run: ls -lh ${JOB_CACHE_PATH}/
      - run: |
          for i in ${JOB_CACHE_PATH}/tempfile-*; do
            echo "file: $i";
            cat $i;
          done
      - run: echo "done"

  stage2:
    needs: stage1
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2    
      - name: Cache tmp folder
        id: cache-tmp
        uses: actions/cache@v3
        with:
          path: ${{ env.JOB_CACHE_PATH }}
          key: ${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ env.RESTORE_KEY }}
      - run: cat ${JOB_CACHE_PATH}/tempfile-${COMMIT_SHA}
