name: "child-name"

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
      version:
        required: false
        type: string
    secrets:
      token:
        required: false

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    run-name: child-${{ inputs.version }}
    steps:
      - name: some stuff
        run: |
          echo "echo ${{ inputs.config-path }}"