name: "child-name"

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
      version:
        required: false
        type: string
      description:
        required: false
        type: string
      child-item-id:
        required: false
        type: string
      auth:
        required: false
        type: string
      check-a-env:
        required: false
        type: string
      check-b-env:
        required: false
        type: string
      check-c-env:
        required: false
        type: string
      check-d-env:
        required: false
        type: string
      proxy:
        required: false
        type: string

    secrets:
      token:
        required: false

  
env:
  JOB_CACHE_PATH: /tmp/node-cache-${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  CACHE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}
  RESTORE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}
  PROXY_HOST: "pluto"

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    name: child-${{ inputs.version }}
    steps:

      - name: Before install
        env:
          CONT: pippo
        run: echo ${{ env.CONT || "std" }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
