name: "child-name"

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
      version:
        required: false
        type: string
    secrets:
      token:
        required: false

  
env:
  JOB_CACHE_PATH: /tmp/node-cache-${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  CACHE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}
  RESTORE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}
  PROXY_HOST: "pluto"

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    name: child-${{ inputs.version }}
    steps:
      - name: some stuff
        run: |
          echo "echo ${{ inputs.config-path }}"
      - run: echo ${{ env.PROXY_HOST }}