name: "child-name"

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
      version:
        required: false
        type: string
      description:
        required: false
        type: string
      child-item-id:
        required: false
        type: string
      auth:
        required: false
        type: string
      check-a-env:
        required: false
        type: string
      check-b-env:
        required: false
        type: string
      check-c-env:
        required: false
        type: string
      check-d-env:
        required: false
        type: string
      proxy:
        required: false
        type: string

    secrets:
      token:
        required: false

  
env:
  JOB_CACHE_PATH: /tmp/node-cache-${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  CACHE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}
  RESTORE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}
  PROXY_HOST: "pluto"

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    name: child-${{ inputs.version }}
    steps:
      - name: get context
        uses: ./.github/actions/demo