name: "chrome driver"

on:
  push:
    branches: [ "node-build" ]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
jobs:
  stage0:
    runs-on: ubuntu-22.04
    container:
      image: node:14
    services:
      selenium:
        image: selenium/standalone-chrome

    steps:
      - uses: browser-actions/setup-chrome@latest
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2   
      - run: chrome --version 
      - name: install NPM
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
            cd example; 
            npm install selenium-webdriver
      - run: echo $PATH
      - run: node example/google_search.js
