name: "chrome driver"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
jobs:
  stage0:
    runs-on: ubuntu-22.04
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version 
      - name: install NPM
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: node example/google_search
