name: Test (single)

on:
  push:
    branches: [ "node-build-dispatch" ]


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: node:16

    services:
      selenium:
        image: selenium/standalone-chrome

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run test
        env:
          BROWSER: chrome
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: screenshots/
