on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
  push:
    branches: 
      - ref-naming-on-pr
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
jobs:
  print-branch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo BRANCH NAME= ${{ github.ref_name || github.head_ref }}