name: "artifacts"

on:
  push:
    branches: [ "*"]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
env:
  JOB_CACHE_PATH: /tmp/node-cache-${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  CACHE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}
  RESTORE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}


jobs:
  demo-action:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all    
      - run: ls -R
      - name: demo
        uses: ./.github/actions/demo


  test-matrix:


  e2e:
    timeout-minutes: 25
    name: "e2e: ${{ matrix.e2e-test.description }}"
    needs: [ playwright ]
    runs-on: ubuntu-22.04
    strategy: 
      fail-fast: false
      matrix:        
        e2e-test:
          - description: "Core"
            name: "core"
            folder: "core"
            provider: "ALL"
            auth: "OAUTH"
            check-cs-env: "true"
            check-ps-env: "true"
            proxy: $PROXY_HOST_BPM            
          - description: "Content: Components"
            name: "content-services"
            folder: "content-services/components"
            provider: "ECM"
            auth: "BASIC"
            check-cs-env: "true"
            proxy: $PROXY_HOST_BPM            
          - description: "Content: Directives"
            name: "content-services"
            folder: "content-services/directives"
            provider: "ECM"
            auth: "BASIC"
            check-cs-env: "true"
            proxy: $PROXY_HOST_BPM            


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all


      - name: debug
        run: |
          echo '${{ toJson(matrix) }}'
      - name: test
      uses: ./.github/actions/test
      with:
        e2e-test-name: ${{ matrix.e2e-test.name }}
        e2e-test-folder: ${{ matrix.e2e-test.folder }}
        e2e-test-provider: ${{ matrix.e2e-test.provider }}
        e2e-test-auth: ${{ matrix.e2e-test.auth }}
        proxy: ${{ matrix. }}
        upload-to-s3: false
        download-from-s3: false


    uses: .github/workflows/demo-workflow.yml
    with:
        e2e-test-name: ${{ matrix.e2e-test.name }}
        e2e-test-folder: ${{ matrix.e2e-test.folder }}
        e2e-test-provider: ${{ matrix.e2e-test.provider }}
        e2e-test-auth: ${{ matrix.e2e-test.auth }}
    secrets:
      envPAT: ${{ secrets.envPAT }}


      # - name: Debug on failure
      #   uses: mxschmitt/action-tmate@v3

      #   if: ${{ failure() }}
      #   with:
      #     timeout-minutes: 60
      #     limit-access-to-actor: true          