on:
  push:
    branches: ["devel"]

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ciao"
  submitted-and-approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "merge approved"

  submitted-but-not-yet-approved:
    if: github.event.review.state != 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "merge not yet approved"
