on:
  push:
    branches: ["devel*"]
  pull_request:
    branches: ["devel*"]

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - run: echo "basic PUSH commit"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"


  submitted-and-draft:
    if: github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo ${{ github.event.review.state }}
          echo ${{ toJson(github.event.review) }}
        name: "review state"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  submitted-and-draft-1:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.review.state }}      
        name: "review state"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  submitted-and-approved:
    if: github.event_name == 'pull_request' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "merge approved"
      - run: echo ${{ github.event.review.state }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"


  submitted-but-not-yet-approved:
    if: ${{ github.event_name == 'pull_request' && github.event.review.state != 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "merge not yet approved"
      - run: echo ${{ github.event.review.state }}
        name: review state
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

