name: "dev-build"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
env:
  JOB_CACHE_PATH: /tmp/node-cache-${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  CACHE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}
  RESTORE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}


jobs:
  job0:
    runs-on: ubuntu-22.04
    env:
      RUN_ID: ${{ github.id }}
      RUN_NUMBER: ${{ github.run_number }}
      JOB_ID: ${{ github.job_id }}
      JOB_NUMBER: ${{ github.run_number }}
    steps:
      - name: echo RUN id, number
        run: "echo RUN ID: $RUN_ID, NUMBER: $RUN_NUMBER" 
      - name: echo JOB id
        run: "echo JOB ID: $RUN_ID"
  job1:
    runs-on: ubuntu-22.04
    env:
      RUN_ID: ${{ github.id }}
      RUN_NUMBER: ${{ github.run_number }}
      JOB_ID: ${{ github.job_id }}
      JOB_NUMBER: ${{ github.run_number }}
    steps:
      - name: echo RUN id, number
        run: "echo RUN ID: $RUN_ID, NUMBER: $RUN_NUMBER" 
      - name: echo JOB id
        run: "echo JOB ID: $RUN_ID"
