on:
  push:
    branches: [ "ids" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
  
env:
  JOB_CACHE_PATH: /tmp/node-cache-${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  CACHE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}
  RESTORE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}


jobs:
  job0:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "event name -> '${{ github.event_name }}'
      - run: echo "context -> '${{ github }}'
      - name: echo RUN id, number
        run: "echo RUN ID: '${{ github.run_id }}', NUMBER: '${{ github.run_number }}'" 
      - name: echo JOB id
        run: "echo JOB ID: '${{ jobs.job_id }}'"
