name: wf
on:
  workflow_call:
    inputs:
      devel:
        description: 'enable pipeline devel'
        required: true
        type: string
        default: "false"
  push:
    branches:
      - input-flag
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - name: output flags
        id: set-matrix
        run: |
            echo devel=${{ inputs.devel }}