name: release-workflow

on:
  workflow_call:
    inputs:
      devel:
        description: 'enable pipeline devel'
        required: false
        type: boolean
        default: false
      dry-run:
        description: 'enable dry-run devel'
        required: false
        type: boolean
        default: false

  push:
    branches:
      - input-flag


jobs:

  build-deploy-and-release-docker-images:
    uses: ./.github/workflows/reusable-workflow.yml
    secrets: inherit
    with:
      devel: ${{ inputs.devel || 'false' }}
      dry-run: ${{ inputs.dry-run || 'false' }}
