name: release-workflow

on:
  workflow_call:
    inputs:
      devel:
        description: 'enable pipeline devel'
        required: true
        type: string
        default: "false"
      dry-run:
        description: 'enable dry-run devel'
        required: true
        type: string
        default: "false"

  push:
    branches:
      - input-flag


jobs:

  build-deploy-and-release-docker-images:
    uses: ./.github/workflows/reusable-workflow.yml
    secrets: inherit
    with:
      devel: ${{ github.event.inputs.devel }}
      dry-run: "false"
