name: "artifacts"

on:
  push:
    branches: [ "*"]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
env:
  JOB_CACHE_PATH: /tmp/node-cache-${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  CACHE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}
  RESTORE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}
  PROXY_HOST: "pluto"

jobs:
  demo-action:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all    
      - run: ls -R



  call-workflow-on-matrix:
    name: "e2e: ${{ matrix.child-item.version }}"
    strategy:
      matrix:        
        child-item:
          - description: "Child core"
            test-id: "core"
            auth: "OAUTH"
            check-a-env: "true"
            check-b-env: "true"
            proxy: ${{ env.PROXY_HOST }}
          
    needs: [ demo-action ]
    uses: ./.github/workflows/child-workflow.yml
    secrets: inherit
    with:
      description: ${{ matrix.child-item.description }}  
      child-item-id: ${{ matrix.child-item.test-id }}  
      auth: ${{ matrix.child-item.auth }}  
      check-a-env: ${{ matrix.child-item.check-a-env }}  
      check-b-env: ${{ matrix.child-item.check-b-env }}  
      check-c-env: ${{ matrix.child-item.check-c-env }}  
      check-d-env: ${{ matrix.child-item.check-d-env }}  
      proxy: ${{ matrix.child-item.proxy }}  
      config-path: .github/labeler-${{ matrix.child-item.version }}.yml
      version: ${{ matrix.child-item.version }}
