on:
  branches: 
    - "devel*"

  pull_request_review:
    types: [submitted]
    
jobs:
  PR-review-approved:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR approved"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"