on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
jobs:
  build-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: jq --version
      - id: print-affected
        run: |
          cat affected.json | jq -c '.projects[:3] | { projects: [ {name: .[]} ] }' > small-affected.json
      - run: |
          cat small-affected.json | jq
      - name: set matrix
        id: set-matrix
        run: |
          JSON=$(cat small-affected.json)
          echo "matrix=${JSON}" >> $GITHUB_OUTPUT

    
  use-matrix:
    needs: build-matrix
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - id: use-affected
        run: |
          echo " running project: ${{ matrix }}"
