on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
jobs:
  read-ref:
    timeout-minutes: 15
    if: github.event.pull_request.merged == true || ${{ inputs.dry-run-release }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/read-ref
      - id: print-affected
        run: |
          cat affected.json | jq '{ projects: .projects[:3] }' > small-affected.json
      - id: use-affected
          needs: print-affected
          strategy:
            matrix: ${{ fromJson(small-affected.json) }}