on:
  push:
    branches: [ "star-escape" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
jobs:
  escape:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: |
          MSG=$(git log --format=%B -n 1 ${{github.event.after}})
          echo "$MSG"
          echo COMMIT_MESSAGE="$MSG" >> "$GITHUB_ENV"
      - run: |
          echo "$COMMIT_MESSAGE"