on:
  push:
    branches: [ "setup-chrome" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
jobs:
  install-chrome:
    runs-on: ubuntu-22.04
    steps:
      - run: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb
      - run: |
            echo "========using google-chrome"
            google-chrome --version || true
            echo "========using chrome"
            chrome --version || true


  retries:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: |
          yq '.. style="" | .env' './.github/variables/variables.yml' | sed s'/: /=/'g > tmp
          while read ENVVAR; do
            echo "$(eval echo $ENVVAR)" >> $GITHUB_ENV
          done < "tmp"
      # - uses: ./.github/actions/read-env-var
      - run: env | sort
    # - name: run test with retries
    #   env:
    #     COUNTER: 0
    #   uses: nick-fields/retry@v2.8.2
    #   with:
    #     timeout_minutes: 20
    #     max_attempts: 3
    #     shell: bash
    #     command: |
    #       echo "++NEW TRY++"
    #       COUNTER=$(cat ${GITHUB_OUTPUT} | grep -E '^[0-9]{1,2}$' | tail -n1)
    #       echo "COUNTER = <$COUNTER>"
    #       exit 1
