on:
  workflow_call:
    inputs:
      devel:
        description: 'enable pipeline devel'
        required: false
        type: boolean
        default: true
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - name: output flags
        id: set-matrix
        run: |
            echo devel=${{ inputs.devel }}