on:
  push:
    branches: [ "strings" ]

  
jobs:
  read-ref:
    timeout-minutes: 15
    if: github.event.pull_request.merged == true || ${{ inputs.dry-run-release }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/read-ref
      - name: Get author name
        id: author
        run: echo "::set-output name=author::$(git show -s --format=%an)"      
      - name: Log levels
        run: |
          echo "::debug::This is a debug message"
          echo "This is an info message"
          echo "::warning::This is a warning"
          echo "::error::This is an error"    
      - name: Log grouping
        run: |
          echo "::group::Group name"
          echo "Log entry"
          echo "::warning::Warning message"
          echo "::endgroup::"
          echo "Outside the group"    
      - name: Mask sensitive data
        run: |
          echo "::add-mask::password123"
          echo "My password is password123"
          echo "::add-mask::$SUPER_SECRET"
          echo "Here's a secret for you: $SUPER_SECRET"    
        env:
          SUPER_SECRET: The cake is a lie.

      - id: login-ecr
        run: |
          echo "::debug::Set the Octocat variable"
          echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::add-mask::Mona The Octocat"
          echo "::workflow-command parameter1={data},parameter2={data}::{command value}"

          echo registry=pippo >> $GITHUB_OUTPUT
          echo IMAGE_NAME=app >> $GITHUB_ENV
          echo IMAGE_TAG=latest >> $GITHUB_ENV
          echo APP_RELEASE_TAG=release-tag >> $GITHUB_ENV
      - name: Set docker tag list
        shell: bash
        run: |
          AWS_ECR_REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          if [[  'true' ]]; then
            echo "mocking ecr login"
            AWS_ECR_REGISTRY=mocked.ecr.io/alfresco
          fi
          if [[ $BRANCH_NAME == "HXOR-563-develop" && ${{ contains(github.event.head_commit.message , '[ci:release') }} == "false" ]]; then
            MULTILINE="$MULTILINE
                        ghcr.io/alfresco/${{ env.IMAGE_NAME }}:HXOR-563-develop-${{ github.run_id }}
                        quay.io/alfresco/${{ env.IMAGE_NAME }}:HXOR-563-develop-${{ github.run_id }}
                        $AWS_ECR_REGISTRY/${{ env.IMAGE_NAME }}:HXOR-563-develop-${{ github.run_id }}"
          fi

          if [[ true == "true" ]]; then
          # on HXOR-563-develop AND HXOR-563-develop-patch*, on release, will build image_name:HXOR-563-develop-7.11.0
            MULTILINE="$MULTILINE
                        ghcr.io/alfresco/${{ env.IMAGE_NAME }}:HXOR-563-develop-${{ env.APP_RELEASE_TAG }}
                        quay.io/alfresco/${{ env.IMAGE_NAME }}:HXOR-563-develop-${{ env.APP_RELEASE_TAG }}
                        $AWS_ECR_REGISTRY/${{ env.IMAGE_NAME }}:HXOR-563-develop-${{ env.APP_RELEASE_TAG }}"
          fi

          echo "$MULTILINE"
