on:
  push:
    branches: [ "strings" ]

  
jobs:
  read-ref:
    timeout-minutes: 15
    if: github.event.pull_request.merged == true || ${{ inputs.dry-run-release }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/read-ref
      - id: login-ecr
        run: |
          echo registry=pippo >> $GITHUB_OUTPUT
          echo IMAGE_NAME=app >> $GITHUB_ENV
          echo IMAGE_TAG=latest >> $GITHUB_ENV
          echo APP_RELEASE_TAG=release-tag >> $GITHUB_ENV
      - name: Set docker tag list
        shell: bash
        run: |
          AWS_ECR_REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          if [[  'true' ]]; then
            echo "mocking ecr login"
            AWS_ECR_REGISTRY=mocked.ecr.io/alfresco
          fi
          if [[ $BRANCH_NAME == "HXOR-563-develop" && ${{ contains(github.event.head_commit.message , '[ci:release') }} == "false" ]]; then
            MULTILINE="$MULTILINE
                        ghcr.io/alfresco/${{ env.IMAGE_NAME }}:HXOR-563-develop-${{ github.run_id }}
                        quay.io/alfresco/${{ env.IMAGE_NAME }}:HXOR-563-develop-${{ github.run_id }}
                        $AWS_ECR_REGISTRY/${{ env.IMAGE_NAME }}:HXOR-563-develop-${{ github.run_id }}"
          fi

          # on HXOR-563-develop AND HXOR-563-develop-patch*, on release, will build image_name:HXOR-563-develop-7.11.0
          if [[ ${{ contains(github.event.head_commit.message , '[ci:release') }} == "true" ]]; then
            MULTILINE="$MULTILINE
                        ghcr.io/alfresco/${{ env.IMAGE_NAME }}:HXOR-563-develop-${{ env.APP_RELEASE_TAG }}
                        quay.io/alfresco/${{ env.IMAGE_NAME }}:HXOR-563-develop-${{ env.APP_RELEASE_TAG }}
                        $AWS_ECR_REGISTRY/${{ env.IMAGE_NAME }}:HXOR-563-develop-${{ env.APP_RELEASE_TAG }}"
          fi

          echo "$MULTILINE"
