on:
  push:
    branches: [ "strings" ]

  
jobs:
  read-ref:
    timeout-minutes: 15
    if: github.event.pull_request.merged == true || ${{ inputs.dry-run-release }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/read-ref
      - name: commit msg
        run: |
          MSG=$(git log --format=%B -n 1 0716190c31c484ae6ca321c44b0f9180724de74c)
          echo "COMMIT_MESSAGE=$MSG" > $GITHUB_ENV
        shell: zsh {0}
