on:
  workflow_call:
  inputs:
    e2e-test-name:
      description: "Test name"
      required: true
    e2e-test-folder:
      description: "Test folder"
      required: true
    e2e-test-provider:
      description: "Test provider"
      required: true
    e2e-test-auth:
      description: "Test auth"
      required: true

    secrets:
      envPAT:
        required: true


jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: some stuff
        env:
          FOLDER: "${{ inputs.e2e-test-folder }}"
          PROVIDER: "${{ inputs.e2e-test-provider }}"
          AUTH_TYPE: "${{ inputs.e2e-test-auth }}"
          E2E_TEST_NAME: "${{ inputs.e2e-test-name }}"
          PROXY_HOST_BPM: ${{ inputs.proxy }}    
        run: |
          echo "input ps cloud ${{ inputs.check-ps-cloud-env }}""
          env | sort