
name: "artifacts"

on:
  push:
  
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  

jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      - uses: ozeta/actions-playground/.github/actions/travis-event-type-load@action/travis-env-parse
        with:
          event_name: schedule
      