
name: "artifacts"

on:
  push:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  

jobs:
  test-action-with-cron:
    runs-on: ubuntu-latest
    env:
      EVENT: crona
    steps:
      - uses: ozeta/actions-playground/.github/actions/travis-event-type-load@action/travis-env-parse
        with:
          event_name: schedule
      - run: echo $TRAVIS_EVENT_TYPE
      - name: test cron 
        run:  if [[ "$TRAVIS_EVENT_TYPE" != "$EVENT" ]]; then exit 1; fi