
name: "travis-event-type-load"

on:
  push:
  workflow_dispatch:
    inputs:
      ORACLE:
        description: 'this is the oracle for the tests'
        required: false
        default: ''
        type: choice
        options:
          - pull_request
          - push
          - cron
          - repository_dispatch
          - workflow_dispatch
  

jobs:
  test-action-with-cron:
    runs-on: ubuntu-latest
    env:
      ORACLE: cron
      TRAVIS_TEST_VALUE: schedule
    steps:
      - uses: ozeta/actions-playground/.github/actions/travis-event-type-load@action/travis-env-parse
        with:
          event_name: $TRAVIS_TEST_VALUE
      - run: echo $TRAVIS_EVENT_TYPE
      - name: test cron 
        run:  if [[ "$TRAVIS_EVENT_TYPE" != "$ORACLE" ]]; then exit 1; fi
  test-action-with-pull-request:
    runs-on: ubuntu-latest
    env:
      ORACLE: pull_request
      TRAVIS_TEST_VALUE: pull_request
    steps:
      - uses: ozeta/actions-playground/.github/actions/travis-event-type-load@action/travis-env-parse
        with:
          event_name: $TRAVIS_TEST_VALUE
      - run: echo $TRAVIS_EVENT_TYPE
      - name: test cron 
        run:  if [[ "$TRAVIS_EVENT_TYPE" != "$ORACLE" ]]; then exit 1; fi
  test-action-with-push:
    runs-on: ubuntu-latest
    env:
      ORACLE: push
      TRAVIS_TEST_VALUE: push
    steps:
      - uses: ozeta/actions-playground/.github/actions/travis-event-type-load@action/travis-env-parse
        with:
          event_name: $TRAVIS_TEST_VALUE
      - run: echo $TRAVIS_EVENT_TYPE
      - name: test cron 
        run:  if [[ "$TRAVIS_EVENT_TYPE" != "$ORACLE" ]]; then exit 1; fi
  test-action-with-default:
    runs-on: ubuntu-latest
    env:
      ORACLE: push
    steps:
      - uses: ozeta/actions-playground/.github/actions/travis-event-type-load@action/travis-env-parse
        with:
          event_name: $TRAVIS_TEST_VALUE
      - run: echo $TRAVIS_EVENT_TYPE
      - name: test cron 
        run:  if [[ "$TRAVIS_EVENT_TYPE" != "$ORACLE" ]]; then exit 1; fi
  test-action-with-repository_dispatch:
    runs-on: ubuntu-latest
    env:
      ORACLE: api
      TRAVIS_TEST_VALUE: repository_dispatch
    steps:
      - uses: ozeta/actions-playground/.github/actions/travis-event-type-load@action/travis-env-parse
        with:
          event_name: $TRAVIS_TEST_VALUE
      - run: echo $TRAVIS_EVENT_TYPE
      - name: test cron 
        run:  if [[ "$TRAVIS_EVENT_TYPE" != "$ORACLE" ]]; then exit 1; fi
  test-action-with-workflow_dispatch:
    runs-on: ubuntu-latest
    env:
      ORACLE: api
      TRAVIS_TEST_VALUE: workflow_dispatch
    steps:
      - uses: ozeta/actions-playground/.github/actions/travis-event-type-load@action/travis-env-parse
        with:
          event_name: $TRAVIS_TEST_VALUE
      - run: echo $TRAVIS_EVENT_TYPE
      - name: test cron 
        run:  if [[ "$TRAVIS_EVENT_TYPE" != "$ORACLE" ]]; then exit 1; fi
