
name: "artifacts"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  

jobs:
  job0:
    runs-on: ubuntu-latest
    env: 
      TRAVIS_EVENT_TYPE: schedule
    steps:
      - uses: .github/actions/travis-event-type-load
      