on:
  push:


  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        - error
  
env:
  JOB_CACHE_PATH: /tmp/node-cache-${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  CACHE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}
  RESTORE_KEY: ${{ github.workspace }}-${{ github.ref_name }}-${{ github.sha }}


jobs:
  job0:
    runs-on: ubuntu-22.04
    outputs:
      tag_sha: ${{ steps.sha_out.outputs.tag_sha }}    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: debug
        run: git tag --sort=-creatordate | head -n 1
      - name: debug
        run: git rev-list -n 1 $(git tag --sort=-creatordate | head -n 1)
      - name: get tag short sha
        id: sha_out
        run: | 
          tag_sha=$(git rev-list -n 1 $(git tag --sort=-creatordate | head -n 1))
          echo "tag_sha=$tag_sha" >> $GITHUB_ENV
          echo "tag_sha=$tag_sha" >> $GITHUB_OUTPUT
          echo $tag_sha
      - name: use sha
        run: |
          echo "output tag sha: '${{ steps.sha_out.outputs.tag_sha }}'"
          echo "env tag sha: '${{ env.tag_sha }}'"